[package]
name = "littlefs2-sys"
description = "Low-level bindings to LittleFS"
version = "0.1.0"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"
categories = ["embedded", "filesystem", "no-std"]
repository = "https://github.com/nickray/littlefs2-sys"

[dependencies]
cty = "0.2.1"

[build-dependencies]
bindgen = "0.52.0"
cc = "1.0.25"
